ALTER TABLE orders ADD COLUMN IF NOT EXISTS info text;
ALTER TABLE orders ALTER COLUMN customer_name SET DEFAULT '';
ALTER TABLE orders ALTER COLUMN phone SET DEFAULT '';
ALTER TABLE orders ALTER COLUMN address SET DEFAULT '';
ALTER TABLE orders ALTER COLUMN governorate SET DEFAULT '';